# Generated by Django 3.2.8 on 2021-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZarcoApp', '0002_remove_user_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Imagen de Perfil'),
        ),
    ]
