# Generated by Django 3.2.8 on 2021-10-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZarcoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria_FK',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='ZarcoApp.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar_FK',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='ZarcoApp.lugar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento_FK',
            field=models.ForeignKey(default=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='ZarcoApp.tipoeve'),
        ),
    ]
