# Generated by Django 3.2.8 on 2021-10-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZarcoApp', '0002_auto_20211017_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='categoria_FK',
            new_name='categoria_FK_id',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='lugar_FK',
            new_name='lugar_FK_id',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='tipoEvento_FK',
            new_name='tipoEvento_FK_id',
        ),
    ]
