# Generated by Django 3.2.7 on 2021-10-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZarcoApp', '0005_auto_20211017_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipoEvento_FK',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='evento_tipo', to='ZarcoApp.tipoeve'),
        ),
    ]
